# Generated by Django 3.2.2 on 2021-05-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='films',
            name='file_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genres'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
