# Generated by Django 3.2.2 on 2021-05-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210519_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='age',
            field=models.CharField(max_length=10, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='films',
            name='date_release',
            field=models.CharField(max_length=20, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='films',
            name='file_image',
            field=models.ImageField(upload_to='img/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='films',
            name='raiting',
            field=models.CharField(max_length=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='age',
            field=models.CharField(max_length=10, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_release',
            field=models.CharField(max_length=20, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='file_image',
            field=models.ImageField(upload_to='img/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='raiting',
            field=models.CharField(max_length=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Films_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('raiting', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('date_release', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('age', models.CharField(max_length=10, verbose_name='Возрастное ограничение')),
                ('file_image', models.ImageField(upload_to='img/', verbose_name='file')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
