# Generated by Django 3.2.3 on 2021-05-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210520_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Фильм на главной страничке', 'verbose_name_plural': 'Фильмы на главной страничке'},
        ),
    ]
