# Generated by Django 3.2.2 on 2021-05-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_films_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_for_storing_movies_from_the_film_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=30, verbose_name='Название')),
                ('movie_description', models.TextField(verbose_name='Описание')),
                ('movie_raiting', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('movie_date_release', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('movie_age_limit', models.CharField(max_length=10, verbose_name='Возрастное ограничение')),
                ('path_to_the_image', models.ImageField(upload_to='img/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Фильм на страничке с фильмами',
                'verbose_name_plural': 'Фильмы на страничке с фильмами',
            },
        ),
        migrations.CreateModel(
            name='Model_for_storing_movies_from_the_main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=30, verbose_name='Название фильма')),
                ('movie_description', models.TextField(verbose_name='Описание')),
                ('movie_raiting', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('movie_date_release', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('movie_age_limit', models.CharField(max_length=10, verbose_name='Возрастное ограничение')),
                ('path_to_the_image', models.ImageField(upload_to='img/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Фильм на главной страничке',
                'verbose_name_plural': 'Фильмы на главной страничке',
            },
        ),
        migrations.CreateModel(
            name='Model_for_storing_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_title', models.CharField(max_length=30, verbose_name='Название')),
                ('serial_description', models.TextField(verbose_name='Описание')),
                ('serial_raiting', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('serial_date_release', models.CharField(max_length=20, verbose_name='Дата выхода')),
                ('serial_age_limit', models.CharField(max_length=10, verbose_name='Возрастное ограничение')),
                ('path_to_the_image', models.ImageField(upload_to='img/', verbose_name='file')),
                ('serial_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_series', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Model_for_storing_genres',
        ),
        migrations.RemoveField(
            model_name='films_new',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='Films_new',
        ),
        migrations.DeleteModel(
            name='Serials',
        ),
        migrations.AddField(
            model_name='model_for_storing_movies_from_the_main_page',
            name='movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_series', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='model_for_storing_movies_from_the_film_page',
            name='movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_series', verbose_name='Жанр'),
        ),
    ]
