# Generated by Django 3.2.2 on 2021-05-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210523_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_for_storing_movies_from_the_film_page',
            name='movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='model_for_storing_movies_from_the_main_page',
            name='movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='model_for_storing_series',
            name='serial_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.model_for_storing_genres', verbose_name='Жанр'),
        ),
    ]
