# Generated by Django 3.2.2 on 2021-05-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210523_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_age_limit',
            new_name='movie_age_limit',
        ),
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_date_release',
            new_name='movie_date_release',
        ),
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_description',
            new_name='movie_description',
        ),
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_genre',
            new_name='movie_genre',
        ),
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_raiting',
            new_name='movie_raiting',
        ),
        migrations.RenameField(
            model_name='model_for_storing_series',
            old_name='serial_title',
            new_name='movie_title',
        ),
    ]
